---
title: "Behavior Data Analysis"
author: "Rayna M Harris"
date: "January 14, 2017"
output:
  md_document:
    variant: markdown_github
---

```{r setup, message=F}
## load libraries 
library(tidyr) ## for respahing data
library(plyr) ## for renmaing factors
library(dplyr) ## for filtering and selecting rows
library(reshape2) ## for melting dataframe

## load functions 
source("functions_behavior.R")

```


```{r behaivordata, message=F}
## read intermediate data (raw data from video tracker program analyzed in matlab)
behavior <- read.csv("../data/01_behaviordata.csv", header = T)
## relevel / revaluefactors
behavior$APA <- factor(behavior$APA, levels = c("Yoked", "Same", "Conflict"))
behavior$APA2 <- factor(behavior$APA2, levels = c("YokedSame", "YokedConflict","Same", "Conflict"))
levels(behavior$APA) <- c("control","consistent","conflict")
levels(behavior$APA2) <- c("yoked-consistent","yoked-conflict","consistent","conflict")

## log transformation 
behavior$Time1stEntrLog <- log(behavior$Time1stEntr) 
```

# mean, sd, sqrt

To make the point and line graphs, I must create and merge some data frames
```{r makenewdf}

## number of entrances
behaviorsummaryNumAPA2 <- dplyr::summarise(group_by(behavior, APA2, TrainSessionComboNum), m = mean(NumEntrances), se = sd(NumEntrances)/sqrt(length(NumEntrances)))

## speed
speedsummary <- dplyr::summarise(group_by(behavior, APA2, TrainSessionComboNum), m = mean(Speed1), se = sd(Speed1)/sqrt(length(Speed1)))

## max avoidance time
maxavoid <- dplyr::summarise(group_by(behavior, APA2, TrainSessionComboNum), m = mean(MaxTimeAvoid), se = sd(MaxTimeAvoid)/sqrt(length(MaxTimeAvoid)))

## create the column for faceting
behaviorsummaryNumAPA2$measure <- "Number of Entrances"
speedsummary$measure <- "Speed"
maxavoid$measure <- "Max Avoidance Time"

# rbind
threeplots <- rbind(behaviorsummaryNumAPA2,speedsummary,maxavoid)
```


```{r PCA}
longdata <- makelongdata(behavior)
Z <- longdata[,3:371]
Z <- Z[,apply(Z, 2, var, na.rm=TRUE) != 0]
pc = prcomp(Z, scale.=TRUE)
loadings <- pc$rotation
scores <- pc$x

scoresdf <- makepcadf(behavior) #create the df of pcas
rotationdf <- mkrotationdf(behavior) #loadings for specific factors
behaviormatrix <- behavior[c(20:58)]  # for 2nd pca analysis


scoresdf$PC1 <- scoresdf$PC1 * -1
```

```{r writefiles}
write.csv(behavior, file = "../data/01a_behavior.csv", row.names = FALSE)
write.csv(threeplots, file = "../data/01a_threeplots.csv", row.names = FALSE)
write.csv(scoresdf, file = "../data/01a_scoresdf.csv", row.names = FALSE)
write.csv(rotationdf, file = "../data/01a_rotationdf.csv", row.names = TRUE)
write.csv(behaviormatrix, file = "../data/01a_behaviormatrix.csv", row.names = TRUE)
```
