---
title: "Electrophysiology"
author: "Rayna M Harris"
date: "March 23, 2017"
output:
  md_document:
    variant: markdown_github
---

```{r setup, message=F}
## load libraries 
library(ggplot2) ## for awesome plots!
library(cowplot) ## for some easy to use themes
library(tidyr) ## for respahing data
library(plyr) ## for renmaing factors
library(dplyr) ## for filtering and selecting rows
library(reshape)  ## widen a
library(car) ## for statistics

## load functions 
source("figureoptions.R")

## set output file for figures 
knitr::opts_chunk$set(fig.path = '../figures/03_ephys/')
```

```{r data,  message=F}
## read summarized ephys data and relevel factors
colData <- read.csv("../data/02a_colData.csv", header = T) # for better group names

ephys <- read.csv("../data/03_ephys.csv", header = T)
ephys$Group <- factor(ephys$Group, levels = c("control", "consistent", "conflict"))
ephyslong <- melt(ephys)

## read voltage response data
ephys2 <- read.csv("../data/03_ephys2.csv", header = T)
ephys2long <- read.csv("../data/03_ephys3.csv", header = T)

ephys2$APA <- factor(ephys2$APA, levels = c("control", "consistent", "conflict"))
ephys2long$APA <- factor(ephys2long$APA, levels = c("control", "consistent", "conflict"))
ephys2long$APA2 <- factor(ephys2long$APA2, levels = c("control-consistent", "consistent",  "control-conflict","conflict"))

ephys3 <- left_join(ephys, colData, by = "Mouse")
ephys3 <- na.omit(ephys3)

ephys3$APA2 <- factor(ephys3$APA2, levels = c("yoked_consistent", "consistent",  "yoked_conflict", "conflict"))
levels(ephys3$APA2) <- c("yoked-consistent", "consistent",  "yoked-conflict", "conflict")

ephys3$one <- "Pre-Potentiation"
ephys3$two <- "Early Potentiation"
ephys3$three <- "Late Potentiation"
ephys3$four <- "Max fEPSP"
```


## the data
```{r dataviz}

one <- ephys3 %>%
  ggplot(aes(x=APA2, y=PTP_3_10, fill=APA2)) +  
  geom_violin() + 
  scale_fill_manual(values = colorvalAPA00) + 
  scale_y_continuous(name=NULL,
                     limits = c(100, 300)) + 
  theme_cowplot(font_size = 8, line_size = 0.25)   + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(),
        legend.position="none") +
  facet_wrap(~one)
one
leveneTest(PTP_3_10~APA2, data=ephys3)
summary(aov(ephys3$PTP_3_10 ~ ephys3$APA2))
TukeyHSD(aov(ephys3$PTP_3_10 ~ ephys3$APA2))
  
two <- ephys3 %>%
  ggplot(aes(x=APA2, y=EarlyPotentiation_11_20, fill=APA2)) +  
  geom_violin() + 
  scale_fill_manual(values = colorvalAPA00) + 
  scale_y_continuous(name=NULL,
                     limits = c(100, 300)) + 
  theme_cowplot(font_size = 8, line_size = 0.25)   + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(),
        legend.position="none") +
  facet_wrap(~two)
two
leveneTest(EarlyPotentiation_11_20~APA2, data=ephys3)
summary(aov(ephys3$EarlyPotentiation_11_20 ~ ephys3$APA2))
TukeyHSD(aov(ephys3$EarlyPotentiation_11_20 ~ ephys3$APA2))


three <- ephys3 %>%
  ggplot(aes(x=APA2, y=LatePotentiation_26_end, fill=APA2)) +  
  geom_violin() + 
  scale_fill_manual(values = colorvalAPA00) + 
  scale_y_continuous(name=NULL,
                     limits = c(100, 300)) + 
  theme_cowplot(font_size = 8, line_size = 0.25)   + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(),
        legend.position="none") +
  facet_wrap(~three)
three
leveneTest(LatePotentiation_26_end~APA2, data=ephys3)
summary(aov(ephys3$LatePotentiation_26_end ~ ephys3$APA2))
TukeyHSD(aov(ephys3$LatePotentiation_26_end ~ ephys3$APA2))

four <- ephys3 %>%
  ggplot(aes(x=APA2, y=MaxfEPSP, fill=APA2)) +  
  geom_violin() +
  scale_fill_manual(values = colorvalAPA00) + 
  scale_y_continuous(trans = "reverse",
                     limits = c(-0.001 , -0.008),
                     name=NULL) + 
  theme_cowplot(font_size = 8, line_size = 0.25)   + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(),
        legend.position="none") +
  facet_wrap(~four)
four
leveneTest(MaxfEPSP~APA2, data=ephys3)
summary(aov(ephys3$MaxfEPSP ~ ephys3$APA2))
TukeyHSD(aov(ephys3$MaxfEPSP ~ ephys3$APA2))

 
pdf(file="../figures/03_ephys/1pre.pdf", width=1.75, height=2)
plot(one)
dev.off()

pdf(file="../figures/03_ephys/2early.pdf", width=1.75, height=2)
plot(two)
dev.off()

pdf(file="../figures/03_ephys/3late.pdf", width=1.75, height=2)
plot(three)
dev.off()

pdf(file="../figures/03_ephys/4max.pdf", width=1.75, height=2)
plot(four)
dev.off()


```



##  one way anova 





```{r plots}
ephys2long %>% 
  ggplot(aes(x=variablenumeric, y=value, color=APA )) + 
  stat_smooth(alpha=0.2, size=1) +
  geom_jitter(size=2, width = 0.5) +
  background_grid(major = "xy", minor = "none") + 
  theme_cowplot(font_size = 20, line_size = 1) + 
  scale_y_continuous(trans = "reverse") + 
  scale_x_continuous(breaks=c(1,2,3,4,5,6,7),
                     labels=c("0", "10", "15", "20", "30", "40", "50")) +
  scale_color_manual(values = colorvalAPA) + 
  labs(x = "Stimulus Strenght (V)", y = "fEPSP Slope") + 
  theme(legend.position="none")


```