---
title: "Integration"
author: "Rayna M Harris"
date: "March 23, 2017"
output:
  md_document:
    variant: markdown_github
---

## Setup
```{r setup, message=F}
library(plyr)
library(dplyr)
library(reshape2)
library(superheat)
library("Hmisc")
library("corrplot")
library("PerformanceAnalytics")
library(viridis)
library(cowplot)
library(pheatmap)

source("figureoptions.R")

knitr::opts_chunk$set(fig.path = '../figures/04_integration/')

```

## Import Data
```{r importdata}
behaviorpca <- read.csv("../data/01a_scoresdf.csv", header = T)
behavior <- read.csv("../data/01a_behavior.csv", header = T)

pcadata <- read.csv("../data/02a_pcadata.csv", header = T)
pcadata$Punch <- ifelse(grepl("DG", pcadata$group), "DG", 
                                        ifelse(grepl("CA3", pcadata$group), "CA3","CA1"))
names(pcadata)[names(pcadata)=="name"] <- "RNAseqID"

rossetta <- read.csv("../data/00_rossettastone.csv", header = F)

colData <- read.csv("../data/02a_colData.csv", header = T) # for better group names

ephys3 <- read.csv("../data/03_ephys.csv", header = T)
ephys3 <- ephys3[,(c(1:6))]

names(ephys3)[3] <- "Pre_Potentiation"
names(ephys3)[4] <- "Early_Potentiation"
names(ephys3)[5] <- "Late_Potentiation"
names(ephys3)[6] <- "Max_fEPSP"
```


```{r metadata}
# clearnup the rosetts data and filter extraneous samples
names(rossetta)[1] <- "organism"
names(rossetta)[2] <- "ID"
names(rossetta)[3] <- "Region"
names(rossetta)[4] <- "RNAseqID"
names(rossetta)[5] <- "R1filename"
rossetta$R2filename <- rossetta$R1filename
rossetta$R2filename <- gsub("R1", "R2", rossetta$R2filename)

## previously used for the Dissocation Test. No longer functional
#rossetta$Mouse <- gsub("15-101", "15-100", rossetta$Mouse)
#write.csv(rossetta, "../../DissociationTest/data/00_metadata.csv")

colData$RNAseqID <- revalue(colData$RNAseqID, c("142C_CA1" = "142C-CA1-S")) 
colData$RNAseqID <- revalue(colData$RNAseqID, c("142C_DG" = "142C-DG-S")) 
colData$RNAseqID <- revalue(colData$RNAseqID, c("143C_CA1" = "143C-CA1-S")) 
colData$RNAseqID <- revalue(colData$RNAseqID, c("143C_DG" = "143C-DG-S"))

metadata <- full_join(colData, rossetta)
names(metadata)[1] <- "samplename"
metadata$title <- as.factor(paste(metadata$ID,metadata$Region, metadata$Group, sep=" "))
names(metadata)[6] <- "sourcename"
metadata$char1 <- "Mus musculus"
metadata$char2 <- "C57BL/6"
metadata$mol <- "RNA"
metadata$des <- " "
metadata$processes <- as.factor(paste(metadata$samplename,"/abundance.txt"))
metadata$process2 <- "IntegrativeWT2015ColData.csv"
str(metadata)

metadata <- select(metadata, samplename, title, sourcename, organism, char1, char2, mol, des, processes, R1filename, R2filename, process2)

#write.csv(metadata, "../data/00_metadata.csv")
```


## Wrangle Data
```{r wrangledata}
# clearnup the rosetts data and filter extraneous samples
names(rossetta)[1] <- "Mouse"
names(rossetta)[2] <- "ID"
names(rossetta)[3] <- "Region"
names(rossetta)[4] <- "RNAseqID"
names(rossetta)[5] <- "R1filename"
rossetta$R1filename <- NULL
rossetta <- rossetta %>% dplyr::filter(Mouse != "15-100", Mouse != "15-101", Mouse != "15-147")
head(rossetta) # dictionary of names


## slim behavior ephy to top 5 pcs and rename the columsn
behaviorpca <- behaviorpca[(c(1:5,35:36))]
names(behaviorpca)[names(behaviorpca)=="PC1"] <- "Behavior_PC1"
names(behaviorpca)[names(behaviorpca)=="PC2"] <- "Behavior_PC2"
names(behaviorpca)[names(behaviorpca)=="PC3"] <- "Behavior_PC3"
names(behaviorpca)[names(behaviorpca)=="PC4"] <- "Behavior_PC4"
names(behaviorpca)[names(behaviorpca)=="PC5"] <- "Behavior_PC5"

behaviorpca <- behaviorpca %>% dplyr::filter(ID != "15148", ID !=  "15140A", ID !=  "15140B", ID !=  "15140C", ID !=  "15140D", ID !=  "15141C", ID !=  "15141D", ID !=  "15142C", ID !=  "15142D", ID !=  "15142A", ID !=  "15142B", ID !=  "15145C", ID !=  "15145C", ID !=  "15145D", ID !=  "15147A", ID !=  "15147B", ID !=  "15148C", ID !=  "15148D")

#prep before joining
pcadata <- pcadata[(c(11:17,2:10))]
rossetta <- unique(rossetta[ , 1:2 ]) # for joining keop only

#widen then length RNAseq data so each row is an animals
pcadatabyregion <- left_join(pcadata, rossetta)
pcadatabyregion <- pcadatabyregion[(c(17:19,2:16))]
pcadatabyregion <- melt(pcadatabyregion, id = c(1:9))
pcadatabyregion$RegionPC <- as.factor(paste(pcadatabyregion$Punch, pcadatabyregion$variable, sep="_"))
pcadatabyregion <- dcast(pcadatabyregion, Mouse ~ RegionPC)
```


```{r integratedata}

alldata <- left_join(pcadatabyregion, rossetta , by="Mouse")
alldata <- left_join(alldata, behaviorpca, by="ID")
alldata <- left_join(alldata, ephys3, by="Mouse")
```


```{r correlationsAvoidance, warning=F}
alldataslim <- dplyr::filter(alldata, APA2 %in% c("conflict","consistent"))

alldataslim <- alldataslim[,-c(1, 5:10,14:19,23:29,35:36)]
alldataslim <- sapply( alldataslim, as.numeric )

cormat <- rcorr(as.matrix(alldataslim))
res2 <- rcorr(as.matrix(alldataslim))

corrplot(res2$r, type = "lower", order = "hclust", 
        tl.col = "black", tl.srt = 45)

corrplot(res2$r, type="lower", order="hclust",  tl.col = "black", 
        p.mat = res2$P, sig.level = 0.05, insig = "blank")

DEGes <- as.data.frame(cormat$r)
DEGes$group <- c("CA1","CA1","CA1","CA3","CA3","CA3","DG","DG","DG","Behavior","Behavior","Behavior","Behavior","Behavior","Physiology","Physiology","Physiology","Physiology")
df <- as.data.frame(DEGes$group)
names(df)[1] <- "Level"
row.names(df) <- row.names(DEGes)
DEGes$group <- NULL

paletteLength <- 30
myBreaks <- c(seq(min(cormat$r), 0, length.out=ceiling(paletteLength/2) + 1),
              seq(max(cormat$r)/paletteLength, max(cormat$r), length.out=floor(paletteLength/2)))
pheatmap(DEGes, show_colnames=T, show_rownames = T,
         annotation_col = df, annotation_colors = ann_colorsLevel,
         annotation_row = df, 
         #annotation_legend = FALSE,
         annotation_names_row = FALSE, annotation_names_col = FALSE,
         treeheight_row = 0, treeheight_col = 25,
         fontsize = 8, 
         width=2.5, height=2,
         border_color = "grey60" ,
         color = viridis(30),
         #cellwidth = 10, 
         clustering_method="average",
         breaks=myBreaks,
         clustering_distance_cols="correlation",
         clustering_distance_rows="correlation" ,
         main="Cognitively Trainied"
         )

pheatmap(cormat$r, show_colnames=F, show_rownames = T,
         annotation_col = df, annotation_colors = ann_colorsLevel,
         annotation_row = df, 
         annotation_legend = FALSE,
         annotation_names_row = FALSE, annotation_names_col = FALSE,
         treeheight_row = 0, treeheight_col = 12.5,
         fontsize = 6, 
         width=3.5, height=2,
         border_color = "grey60" ,
         color = viridis(30),
         clustering_method="average",
         breaks=myBreaks,
         clustering_distance_cols="correlation",
         clustering_distance_rows="correlation",
         filename = "../figures/04_integration/corrTrained.pdf",
         main="Cognitively Trainied"
         )

alldata$APA2 <- factor(alldata$APA2, levels = c("yoked-consistent", "consistent",  "yoked-conflict", "conflict"))

alldata$avoidance <-  ifelse(grepl("yoked", alldata$APA), "no", "yes")

alldata$wrap <- "All Cognitively Trained" 

behavDG <- alldata %>%
  ggplot(aes(as.numeric(DG_PC2), Behavior_PC1, color=avoidance)) + 
  geom_point(size = 1, alpha = 0.75) +
  scale_color_manual(values = "red") +
    theme_cowplot(font_size = 8, line_size = 0.25)  +
    theme(legend.position="none") +
    stat_smooth(method = "lm") + 
    ylab(paste0("Behavior PC1")) +
    xlab(paste0("DG PC1"))  +
  facet_wrap(~wrap)
behavDG

pdf(file="../figures/04_integration/behavDG.pdf", , width=1.75, height=2)
plot(behavDG)
dev.off()


```



```{r correlationsYoked, warning=F}
alldata <- left_join(pcadatabyregion, rossetta , by="Mouse")
alldata <- left_join(alldata, behaviorpca, by="ID")
alldata <- left_join(alldata, ephys3, by="Mouse")

alldataslim <- dplyr::filter(alldata, APA2 %in% c("yoked-conflict","yoked-consistent"))

alldataslim <- alldataslim[,-c(1, 5:10,14:19,23:29,35:36)]
alldataslim <- sapply( alldataslim, as.numeric )

cormat <- rcorr(as.matrix(alldataslim))
res2 <- rcorr(as.matrix(alldataslim))

corrplot(res2$r, type = "lower", order = "hclust", 
        tl.col = "black", tl.srt = 45)

corrplot(res2$r, type="lower", order="hclust",  tl.col = "black", 
        p.mat = res2$P, sig.level = 0.05, insig = "blank")

DEGes <- as.data.frame(cormat$r)
DEGes$group <- c("CA1","CA1","CA1","CA3","CA3","CA3","DG","DG","DG","Behavior","Behavior","Behavior","Behavior","Behavior","Physiology","Physiology","Physiology","Physiology")
df <- as.data.frame(DEGes$group)
names(df)[1] <- "Level"
row.names(df) <- row.names(DEGes)
DEGes$group <- NULL

paletteLength <- 30
myBreaks <- c(seq(min(cormat$r), 0, length.out=ceiling(paletteLength/2) + 1),
              seq(max(cormat$r)/paletteLength, max(cormat$r), length.out=floor(paletteLength/2)))
pheatmap(DEGes, show_colnames=T, show_rownames = T,
         annotation_col = df, annotation_colors = ann_colorsLevel,
         annotation_row = df, 
         #annotation_legend = FALSE,
         annotation_names_row = FALSE, annotation_names_col = FALSE,
         treeheight_row = 0, treeheight_col = 25,
         fontsize = 8, 
         width=2.5, height=2,
         border_color = "grey60" ,
         color = viridis(30),
         #cellwidth = 10, 
         clustering_method="average",
         breaks=myBreaks,
         clustering_distance_cols="correlation",
         clustering_distance_rows="correlation" ,
         main="All Yoked"
         )

pheatmap(cormat$r, show_colnames=F, show_rownames = T,
         annotation_col = df, annotation_colors = ann_colorsLevel,
         annotation_row = df, 
         annotation_legend = FALSE,
         annotation_names_row = FALSE, annotation_names_col = FALSE,
         treeheight_row = 0, treeheight_col = 12.5,
         fontsize = 6, 
         width=3.5, height=2,
         border_color = "grey60" ,
         color = viridis(30),
         clustering_method="average",
         breaks=myBreaks,
         clustering_distance_cols="correlation",
         clustering_distance_rows="correlation",
         filename = "../figures/04_integration/corrYoked.pdf",
         main="All Yoked"
         )


alldata$wrap <- "All Cognitively Trained" 

behavDG <- alldata %>%
  ggplot(aes(as.numeric(DG_PC2), Behavior_PC1)) + 
  geom_point(size = 1, alpha = 0.75) +
  scale_color_manual(values = c("red")) +
    theme_cowplot(font_size = 8, line_size = 0.25)  +
    theme(legend.position="none") +
    stat_smooth(method = "lm") + 
    ylab(paste0("Behavior PC1")) +
    xlab(paste0("DG PC1"))  +
  facet_wrap(~wrap)
behavDG

pdf(file="../figures/04_integration/behavDG.pdf", , width=1.75, height=2)
plot(behavDG)
dev.off()


```
