---
title: "WGCNA"
author: "Rayna M Harris"
date: "April 30, 2017"
output: html_document
---

```{r setup}
# Install and Load WGCNA package
# https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/faq.html
#source("https://bioconductor.org/biocLite.R")
#biocLite("WGCNA")
#install.packages("flashClust")
library(WGCNA)
library(flashClust)
library(magrittr) ## to use the weird pipe
library("dplyr")

options(stringsAsFactors=FALSE)
allowWGCNAThreads()

## set output file for figures 
knitr::opts_chunk$set(fig.path = '../figures/04_wgcna/')
```

```{r loaddata}
datExpr0 <- read.csv("../data/02a_countData.csv", header = T, check.names = F, row.names = 1)

## make values numbers not integers
cols = c(1:34)
datExpr0[,cols] %<>% lapply(function(x) as.numeric(as.integer(x)))

## remove rows with rowsum > some value
datExpr0 <- datExpr0[rowMeans(datExpr0[, -1])>1, ]

## transpose data
datExpr0 <- t(datExpr0)
datExpr0 <- as.data.frame(datExpr0)

# test that all samples good to go
gsg=goodSamplesGenes(datExpr0, verbose = 1)
gsg$allOK #If the last statement returns TRUE, all genes have passed the cuts
#head(gsg)

#-----Make a trait data frame from just sample info without beahvior
datTraits <- read.csv("../data/02a_colData.csv", header = T)
str(datTraits)
names(datTraits)

datTraits$RNAseqID <- as.integer(factor(datTraits$RNAseqID))
datTraits$Mouse <- as.integer(factor(datTraits$Mouse))
datTraits$Conflict <- as.integer(factor(datTraits$Conflict))
datTraits$Punch <- as.integer(factor(datTraits$Punch))
datTraits$APA <- as.integer(factor(datTraits$APA))
datTraits$ID <- as.integer(factor(datTraits$ID))

datTraits$RNAseqID <- as.numeric(factor(datTraits$RNAseqID))
datTraits$Mouse <- as.numeric(factor(datTraits$Mouse))
datTraits$Conflict <- as.numeric(factor(datTraits$Conflict))
datTraits$Punch <- as.numeric(factor(datTraits$Punch))
datTraits$Slice <- as.numeric(factor(datTraits$Slice))
datTraits$APA <- as.numeric(factor(datTraits$APA))
datTraits$ID <- as.numeric(factor(datTraits$ID))
```


```{r sampleoutliers}
#-----Sample dendrogram and traits
A=adjacency(t(datExpr0),type="signed")
#-----Calculate whole network connectivity
k=as.numeric(apply(A,2,sum))-1

#-----Standardized connectivity
Z.k=scale(k)
thresholdZ.k=-2.5 
outlierColor=ifelse(Z.k<thresholdZ.k,"red","black")
sampleTree = flashClust(as.dist(1-A), method = "average")
#-----Convert traits to colors
traitColors=data.frame(numbers2colors(datTraits,signed=FALSE))
str(traitColors)
dimnames(traitColors)[[2]]=paste(names(datTraits))
datColors=data.frame(outlier=outlierColor,traitColors)

#-----Plot the sample dendrogram
#quartz()
plotDendroAndColors(sampleTree,groupLabels=names(datColors),
                    colors=datColors,main="Sample dendrogram and trait heatmap")


# Plot a line to show the cut
abline(h = 0.7, col = "red");
# Determine cluster under the line
clust = cutreeStatic(sampleTree, cutHeight = 0.7, minSize = 10)
table(clust)
keepSamples = (clust==1)
datExpr = datExpr0[keepSamples, ]
nGenes = ncol(datExpr)
nSamples = nrow(datExpr)

#-----Remove outlying samples 
#remove.samples= Z.k<thresholdZ.k | is.na(Z.k)
#datExpr0=datExpr0[!remove.samples,]
#datTraits=datTraits[!remove.samples,]
#A=adjacency(t(datExpr0),type="distance")
#k=as.numeric(apply(A,2,sum))-1
#Z.k=scale(k)
```

```{r softthreshold}
dim(datExpr0)
dim(datTraits)
powers= c(seq(1,10,by=1), seq(from =12, to=20, by=2)) #choosing a set of soft-thresholding powers
sft = pickSoftThreshold(datExpr0, powerVector=powers, verbose =5,networkType="signed") #call network topology analysis function


#quartz()
par(mfrow= c(1,2))
cex1=0.9
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], xlab= "Soft Threshold (power)", ylab="Scale Free Topology Model Fit, signed", type= "n", main= paste("Scale independence"))
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], labels=powers, cex=cex1, col="red")
abline(h=0.90, col="red")
plot(sft$fitIndices[,1], sft$fitIndices[,5], xlab= "Soft Threshold (power)", ylab="Mean Connectivity", type="n", main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1, col="red")
dev.off()
softPower=20
```

```{r constructnetwork}
adjacency=adjacency(datExpr0, power=softPower, type="signed" ) 
TOM= TOMsimilarity(adjacency, TOMType="signed")
dissTOM= 1-TOM
geneTree= flashClust(as.dist(dissTOM), method="average")
plot(geneTree, xlab="", sub="", main= "Gene Clustering on TOM-based dissimilarity", labels= FALSE, hang=0.04)
```

```{r createmodules}
minModuleSize=100
dynamicMods= cutreeDynamic(dendro= geneTree, distM= dissTOM, deepSplit=2, pamRespectsDendro= FALSE, minClusterSize= minModuleSize)
table(dynamicMods)
dynamicColors= labels2colors(dynamicMods)
plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut", dendroLabels= FALSE, hang=0.03, addGuide= TRUE, guideHang= 0.05, main= "Gene dendrogram and module colors")

#-----Merge modules whose expression profiles are very similar
MEList= moduleEigengenes(datExpr0, colors= dynamicColors)
MEs= MEList$eigengenes
#Calculate dissimilarity of module eigenegenes
MEDiss= 1-cor(MEs, use = 'pairwise.complete.obs')
#Cluster module eigengenes
METree= flashClust(as.dist(MEDiss), method= "average")

#quartz()
plot(METree, main= "Clustering of module eigengenes", xlab= "", sub= "")
MEDissThres = 0.4
abline(h=MEDissThres, col="red")
merge= mergeCloseModules(datExpr0, dynamicColors, cutHeight= MEDissThres, verbose =3)

mergedColors= merge$colors
mergedMEs= merge$newMEs

#quartz()
plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors), c("Dynamic Tree Cut", "Merged dynamic"), dendroLabels= FALSE, hang=0.03, addGuide= TRUE, guideHang=0.05)

moduleColors= mergedColors
colorOrder= c("grey", standardColors(50))
moduleLabels= match(moduleColors, colorOrder)-1
MEs=mergedMEs
```

