---
title: "02e_morecorrelations"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(fig.path = '../figures/02e_correlations/', cache = F)
```


```{r packages}
library(tidyverse)
library(corrr)
library(cowplot)

source("./figureoptions.R")

```


```{r DGDEGs}
ARC_associated <- read_csv("../data/02h_ARC_associated.csv")  %>% mutate_each(funs=toupper)  %>% dplyr::pull(gene) 
Neurod6_associated <- read_csv("../data/02h_Neurod6_associated.csv") %>% mutate_each(funs=toupper)  %>% dplyr::pull(gene) 
Prkcz_associated <- read_csv("../data/02h_Prkcz_associated.csv") %>% mutate_each(funs=toupper)  %>% dplyr::pull(gene) 


DG_DEGs <- read.csv("../data/02f_DG_DEGs_vsd.csv", row.names = 1, check.names = F)
DG_DEGs <- as.data.frame(t(DG_DEGs))
DG_DEGs$sample <- row.names(DG_DEGs)
DG_DEGs <- DG_DEGs %>% select(`1190002N15RIK`:ZFP869)
head(DG_DEGs)[1:5]

DG_DEGs <- as.data.frame(t(DG_DEGs))
DG_DEGs$gene <- row.names(DG_DEGs)

DG_ARC <- DG_DEGs %>% filter(gene %in% ARC_associated) %>% select(gene, everything())
row.names(DG_ARC) <- DG_ARC$gene
DG_ARC$gene <- NULL


DG_ARC <- as.data.frame(t(DG_ARC))
DG_ARC$sample  <- row.names(DG_ARC)
DG_ARC$mouse <- sapply(strsplit(as.character(DG_ARC$sample),"\\-"), "[", 1)
DG_ARC$ID <- paste(15, DG_ARC$mouse, sep = "")

# read the sample data, set levels
colData <- read.csv("../data/02a_colData.csv", row.names = 1, stringsAsFactors = T)
colData <- colData %>% filter(subfield == "DG")

# join with pca data for retention

pca.Rn <- read_csv("../data/01a_pca.all.csv") %>% filter(TrainSessionComboNum == 9)
pca.Rn <- pca.Rn %>% select(ID:PC2)
head(pca.Rn)

colData <- left_join(colData, pca.Rn)
colData

alldata <- left_join(colData, DG_ARC)
forcorplots <- alldata %>% select(PC1:UBC)
forcorplots

x <- correlate(forcorplots)

x %>% filter(PC1 > 0.755) %>% arrange(desc(PC1)) 


plotmycors <- function(df, whichgene, mysubtitle){
 p <- ggplot(alldata, aes(x = PC1, y = whichgene)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   labs(y = mysubtitle,  x = "PC1") +
   theme(legend.position = "none")
 return(p) 
}  



p3 <- plotmycors(alldata, alldata$ARC, "ARC")
p3

ggplot(alldata, aes(x = ARC, y = FOSL2)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")

ggplot(alldata, aes(x = NAF1, y = CPEB4)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")
```


```{r DGvsd}
vsd <- read.csv("../data/02c_DGvsd.csv", row.names = 1, check.names = F)

GOgenes <- read_csv("../data/goterms/GOterms.csv") 
GOgenes

vsd2 <- vsd %>%
  mutate(genes = toupper(rownames(vsd))) %>%
  filter(genes %in% GOgenes$gene) %>%
  as.data.frame()
row.names(vsd2) <- vsd2$genes
vsd2$genes <- NULL
head(vsd2)


vsd <- as.data.frame(t(vsd2))

vsd$sample <- row.names(vsd)
head(vsd)[1]
head(vsd)[6112]
vsd <- vsd %>% select(`1600014C10RIK`:ZYX)
vsd


vsd$sample  <- row.names(vsd)
vsd$mouse <- sapply(strsplit(as.character(vsd$sample),"\\-"), "[", 1)
vsd$ID <- paste(15, vsd$mouse, sep = "")
vsd <- vsd %>% select(ID, `1600014C10RIK`:ZYX)
head(vsd)[1:5]

vsd <- left_join(colData, vsd)
vsd
forcorall <-  vsd %>% select(PC1:ZYX)
y <- correlate(forcorall) 

head(vsd)


y %>% filter(PC1 > 0.6) %>% arrange(desc(PC1)) 
y %>% filter(PC1 < -0.6) %>% arrange(desc(PC1)) 

y %>% filter(PC2 > 0.6) %>% arrange(desc(PC2)) 
y %>% filter(PC2 < -0.6) %>% arrange(desc(PC2)) 

y %>% 
  focus(PC1,PC2, ADRB1, ARC, BDNF, BTG2, EGR1, HMGCR, JUN, NPAS4, NPTX2, PAK6, PLK2, PTGS2, SGK1, SRF, SYT4,  mirror = TRUE)  %>% 
        rplot(shape = 15, colors = c("#67a9cf", "#ef8a62") ) 

y %>% 
  focus(PC1,PC2, ADRB1, ARC, BDNF, BTG2, EGR1, HMGCR, JUN, NPAS4, NPTX2, PAK6, PLK2, PTGS2, SGK1, SRF, SYT4,  mirror = TRUE)  %>% 
        rplot( colors = c("#67a9cf", "#ef8a62") ) 

a1 <- y %>% focus(PC1,PC2, ADRB1, ARC, BDNF, BTG2, EGR1, HMGCR, JUN, NPAS4, NPTX2,
           # PRKCZ, DLG4,
            PAK6, PLK2, PTGS2, SGK1, SRF, SYT4,  mirror = TRUE)  %>% 
  network_plot(colors = c("#67a9cf", "#ef8a62") ) +
  theme(legend.position = "bottom")
a1



a <- ggplot(vsd, aes(x = PC1, y = ARC)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())
b <- ggplot(vsd, aes(x = PC1, y = BDNF)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())
c <- ggplot(vsd, aes(x = PC1, y = PRKCZ)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")  +
  scale_x_continuous(breaks = c(-2,0,2,4,6))
d <- ggplot(vsd, aes(x = PC1, y = DLG4)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
  # theme(axis.text.x = element_blank())  +
   theme(legend.position = "none")  +
  scale_x_continuous(breaks = c(-2,0,2,4,6))
   

a2 <- plot_grid(a,b,c,d, nrow = 2, rel_heights = c(0.45, 0.55))

plot_grid(a1,a2)




```

```{r DGvsd2}
vsd <- read.csv("../data/02c_DGvsd.csv", row.names = 1, check.names = F)

sanesLichtman <- read.csv("../data/02i_sanesLichtman.csv", header = T, stringsAsFactors = F)
head(sanesLichtman)

sanesLichtmangenes <- as.vector(sanesLichtman$gene)

vsd2 <- vsd %>%
  mutate(genes = toupper(rownames(vsd))) %>%
  filter(genes %in% sanesLichtman$gene) %>%
  as.data.frame()
row.names(vsd2) <- vsd2$genes
vsd2$genes <- NULL
head(vsd2)


vsd <- as.data.frame(t(vsd2))

vsd$sample <- row.names(vsd)
head(vsd)[1]
head(vsd)[226]
vsd <- vsd %>% select(`ACHE`:VAMP8)
vsd


vsd$sample  <- row.names(vsd)
vsd$mouse <- sapply(strsplit(as.character(vsd$sample),"\\-"), "[", 1)
vsd$ID <- paste(15, vsd$mouse, sep = "")
vsd <- vsd %>% select(ID, `ACHE`:VAMP8)
head(vsd)[1:5]

vsd <- left_join(colData, vsd)
vsd
forcorall <-  vsd %>% select(PC1:VAMP8)
y <- correlate(forcorall) 


y %>% filter(PC1 > 0.5) %>% arrange(desc(PC1)) 
y %>% filter(PC1 < -0.5) %>% arrange(desc(PC1)) 

y %>% filter(PC2 > 0.5) %>% arrange(desc(PC2)) 
y %>% filter(PC2 < -0.5) %>% arrange(desc(PC2)) 


y %>% 
  focus(PC1,PC2, CREB1,MAPK1 ,EGR1, HOMER1, GABRR1, PRKCZ,GRIA1, GRIN1,GRM1, mirror = TRUE)  %>% 
        rplot(shape = 15, colors = c("#67a9cf", "#ef8a62") ) 

y %>% 
  focus(PC1,PC2, CREB1,MAPK1 ,EGR1, HOMER1, GABRR1, PRKCZ,GRIA1, GRIN1,GRM1,  mirror = TRUE)  %>% 
        rplot( colors = c("#67a9cf", "#ef8a62") ) 






a <- ggplot(vsd, aes(x = PC1, y = CAMK2)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())
b <- ggplot(vsd, aes(x = PC1, y = GRIA1)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())
c <- ggplot(vsd, aes(x = PC1, y = GRM1)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
   theme(legend.position = "none")  +
  scale_x_continuous(breaks = c(-2,0,2,4,6))
d <- ggplot(vsd, aes(x = PC1, y = DLG4)) +
   geom_point(aes( color = treatment)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = treatmentcolors) +
  # theme(axis.text.x = element_blank())  +
   theme(legend.position = "none")  +
  scale_x_continuous(breaks = c(-2,0,2,4,6))
   

a2 <- plot_grid(a,b,c,d, nrow = 2, rel_heights = c(0.45, 0.55))

plot_grid(a1,a2)




```


