---
title: "MULTIQC"
author: "Rayna M Harris"
date: "10/31/2017"
output:  md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)

source("./figureoptions.R")

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = '../figures/02g_MultiQC/')
```

```{r multiqc, fig.width = 6.69, fig.height = 2.4}
# read meta data for plotting
colData <- read.csv("../data/02a_colData.csv")
colData <- colData %>% select(RNAseqID, treatment)  

# stats from fastqc 
fastqc <- read.csv(file = "../data/multiqc/multiqc_fastqc.csv")
fastqc$read <- ifelse(grepl("R1", fastqc$Sample.Name), "R1", "R2")  # make read columns
fastqc$mouse <- sapply(strsplit(as.character(fastqc$Sample.Name),"\\_"), "[", 1)
fastqc$subfield <- sapply(strsplit(as.character(fastqc$Sample.Name),"\\_"), "[", 2)
fastqc$section <- sapply(strsplit(as.character(fastqc$Sample.Name),"\\_"), "[", 3)
fastqc$RNAseqID <- paste(fastqc$mouse, fastqc$subfield, fastqc$section, sep = "-")
fastqc <- left_join(colData,fastqc) %>% 
  select(RNAseqID, treatment, subfield, read, QualityFiltered, Dups, GC, Length, MillionReads)  %>% 
  filter(QualityFiltered == "No")

fastqc$treatment <- factor(fastqc$treatment, levels = levelstreatment)
fastqc$subfield <- factor(fastqc$subfield, levels = levelssubfield)
head(fastqc)

# stats from kallisto
kallisto <- read.csv(file = "../data/multiqc/multiqc_kallisto.csv")
kallisto$mouse <- sapply(strsplit(as.character(kallisto$sample),"\\_"), "[", 1)
kallisto$subfield <- sapply(strsplit(as.character(kallisto$sample),"\\_"), "[", 2)
kallisto$section <- sapply(strsplit(as.character(kallisto$sample),"\\_"), "[", 3)
kallisto$RNAseqID <- paste(kallisto$mouse, kallisto$subfield, kallisto$section, sep = "-")
kallisto <- left_join(colData,kallisto) %>% 
  select(RNAseqID, treatment, subfield, QC, bp, fracalign, millalign) %>% 
  filter(QC == "raw")
kallisto$treatment <- factor(kallisto$treatment, levels = levelstreatment)
kallisto$subfield <- factor(kallisto$subfield, levels = levelssubfield)
head(kallisto)


multiqc <- left_join(fastqc, kallisto) 
multiqc$treatment <-   fct_recode(multiqc$treatment, "standard\nyoked" = "standard.yoked", 
                                  "standard\ntrained" = "standard.trained",
                                  "conflict\nyoked" = "conflict.yoked", 
                                  "conflict\ntrained" = "conflict.trained")
head(multiqc)

a <- ggplot(multiqc, aes(x = treatment, y = MillionReads, color = treatment)) +
  geom_boxplot() + geom_point() +
  scale_color_manual(values = treatmentcolors2) +  
  #facet_wrap(~subfield, nrow = 3) +
  labs(y = "Total Reads (millions)", x = NULL, subtitle = " ") +
  theme_ms() + theme(legend.position = "none")


b <- ggplot(multiqc, aes(x = treatment, y = millalign, color = treatment)) +
  geom_boxplot() + geom_point() +
  scale_color_manual(values = treatmentcolors2) +  
  labs(y = "Pseudo-aligned Reads (millions)", x = NULL, subtitle = " ") +
  theme_ms() + theme(legend.position = "none")

c <- ggplot(multiqc, aes(x = treatment, y = fracalign, color = treatment)) +
         geom_boxplot() + geom_point() +
  scale_color_manual(values = treatmentcolors2) +  
  labs(y = "Fraction aligned (millions)", x = NULL, subtitle = " ") +
  theme_ms() + theme(legend.position = "none")


plot_grid( a, b , c , 
          labels = c( "(a)", "(b)", "(c)"),
          label_size = 8, nrow = 1)


summary(multiqc)

mean(multiqc$MillionReads)
sd(multiqc$MillionReads)

mean(multiqc$millalign)
sd(multiqc$millalign)

mean(multiqc$fracalign)
sd(multiqc$fracalign)

summary(aov(MillionReads ~ treatment, multiqc))
summary(aov(millalign ~ treatment, multiqc))
summary(aov(fracalign ~ treatment, multiqc))





a <- ggplot(multiqc, aes(x = subfield, y = MillionReads, color = subfield)) +
  geom_boxplot() + geom_point() +
  scale_color_manual(values = colorvalsubfield) +  
  #facet_wrap(~subfield, nrow = 3) +
  labs(y = "Total Reads (millions)", x = NULL, subtitle = " ") +
  theme_ms() + theme(legend.position = "none")


b <- ggplot(multiqc, aes(x = subfield, y = millalign, color = subfield)) +
  geom_boxplot() + geom_point() +
  scale_color_manual(values = colorvalsubfield) +  
  labs(y = "Pseudo-aligned Reads (millions)", x = NULL, subtitle = " ") +
  theme_ms() + theme(legend.position = "none")

c <- ggplot(multiqc, aes(x = subfield, y = fracalign, color = subfield)) +
         geom_boxplot() + geom_point() +
  scale_color_manual(values = colorvalsubfield) +  
  labs(y = "Fraction aligned (millions)", x = NULL, subtitle = " ") +
  theme_ms() + theme(legend.position = "none")


plot_grid( a, b , c , 
          labels = c( "(a)", "(b)", "(c)"),
          label_size = 8, nrow = 1)

summary(aov(MillionReads ~ subfield, multiqc))
summary(aov(millalign ~ subfield, multiqc))
summary(aov(fracalign ~ subfield, multiqc))


```




