---
title: "candidate genes"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr) # for sentence to upper case conversion
library(kableExtra) # for pretty tables

knitr::opts_chunk$set(echo = TRUE)
```

Genes from Cembrowski sublement file 1 <https://elifesciences.org/articles/14997/figures>

```{r markergenes}
# import cembrowski markers
cembrowskisupp <- read.table("../data/cembrowksi_markers/elife-14997-supp1-v1_dendrogram.txt", sep="\t", header = T)

# select just columns with gene symbol and enriched column
# then rename gene column and convert to uppercase
cembrowskisupp <- cembrowskisupp %>% dplyr::select(gene_short_name, enriched) 
colnames(cembrowskisupp)[1] <- "gene"
cembrowskisupp$gene <- str_to_upper(cembrowskisupp$gene)
head(cembrowskisupp)

# subset my maker

cembrowksimarkers <- function(subfields){
  mydf <- cembrowskisupp %>% 
  dplyr::filter(enriched %in% subfields) %>% 
  select(gene)
  names(mydf) <- NULL
  mylist <- as.list(mydf[,1])
  return(mylist)
}

levels(cembrowskisupp$enriched)

CA1_markers <- cembrowksimarkers(c("ca1_d", "ca1_v", "ca1_d-ca1_v"))
DG_markers <- cembrowksimarkers(c("dg_d", "dg_v", "dg_d-dg_v"))
CA3_markers <- cembrowksimarkers(c("ca3_d", "ca3_v", "ca3_d-ca3_v-ca2-ca1_d-ca1_v"))
CA2_markers <- cembrowksimarkers(c("ca2"))
CA4_markers <- cembrowksimarkers(c("ca4"))

```


```{r subfieldpvals}
# import subfield specific data
wrangledata <- function(filename, mycomparison){
  mydata <- read.csv(filename, header = T)
  mydata$gene <- str_to_upper(mydata$gene)
  mydata$comparison <- mycomparison
  return(mydata)
}

CA1DG <- wrangledata("../data/DGvCA1.csv", "CA1-DG")
CA1CA3 <- wrangledata("../data/CA3vCA1.csv", "CA1-CA3")
CA3DG <- wrangledata("../data/DGvCA3.csv", "CA3-DG")
```

```{r}
#look for markers in each supfield
# make data frames of genes expression results for markers 
marker_expression <- function(mydf, subfield, markers){
    MARKERS <- str_to_upper(markers)
    df <- mydf %>%
    dplyr::filter(gene %in% c(MARKERS)) %>%
    dplyr::mutate(marker = subfield) %>%
    droplevels()
    return(kable(head(df)))
}

marker_summary <- function(mydf, subfield, markers){
    MARKERS <- str_to_upper(markers)
    df <- mydf %>%
    dplyr::filter(gene %in% c(MARKERS)) %>%
    dplyr::mutate(marker = subfield) %>%
    droplevels()
    return(summary(df$direction))
}


#CA1 markers
marker_expression(CA1DG, "CA1", CA1_markers)
marker_expression(CA1CA3, "CA1", CA1_markers)
marker_expression(CA3DG, "CA1", CA1_markers)

marker_summary(CA1DG, "CA1", CA1_markers)
marker_summary(CA1CA3, "CA1", CA1_markers)
marker_summary(CA3DG, "CA1", CA1_markers)


#CA3 markers
marker_expression(CA1DG, "CA3", CA3_markers)
marker_expression(CA1CA3, "CA3", CA3_markers)
marker_expression(CA3DG, "CA3", CA3_markers)

marker_summary(CA1DG, "CA3", CA3_markers)
marker_summary(CA1CA3, "CA3", CA3_markers)
marker_summary(CA3DG, "CA3", CA3_markers)


#DG markers
marker_expression(CA1DG, "DG", DG_markers)
marker_expression(CA1CA3, "DG", DG_markers)
marker_expression(CA3DG, "DG", DG_markers)

marker_summary(CA1DG, "DG", DG_markers)
marker_summary(CA1CA3, "DG", DG_markers)
marker_summary(CA3DG, "DG", DG_markers)


#CA2 markers
marker_expression(CA1DG, "CA2", CA2_markers)
marker_expression(CA1CA3, "CA2", CA2_markers)
marker_expression(CA3DG, "CA2", CA2_markers)

marker_summary(CA1DG, "CA2", CA2_markers)
marker_summary(CA1CA3, "CA2", CA2_markers)
marker_summary(CA3DG, "CA2", CA2_markers)


#CA4 markers
marker_expression(CA1DG, "CA4", CA4_markers)
marker_expression(CA1CA3, "CA4", CA4_markers)
marker_expression(CA3DG, "CA4", CA4_markers)

marker_summary(CA1DG, "CA4", CA4_markers)
marker_summary(CA1CA3, "CA4", CA4_markers)
marker_summary(CA3DG, "CA4", CA4_markers)

```