---
title: "Correlation Analysis"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(fig.path = '../figures/04_correlations/')
```


```{r packages}
library(tidyverse)
library(corrr)
library(cowplot)
library(Hmisc) # for correlations with pvalue
library(ggrepel)


source("./figureoptions.R")
source("./functions_RNAseq.R")
```

## Sample information and PC1

```{r DGDEGs}
# read the sample data, set levels, join iwth behvior PCA data
colData <- read.csv("../data/00_colData.csv", row.names = 1, stringsAsFactors = T)
colData <- colData %>% filter(subfield == "DG")
pca.Rn <- read_csv("../data/suppletable3.csv") %>% dplyr::filter(trialNum == 9)
colData <- left_join(colData, pca.Rn)
head(colData)
```

```{r DGvsd}
# read all count data
vsd <- read.csv("../data/03_DG_vsdtraining.csv", row.names = 1, check.names = F) 
vsd$gene <- row.names(vsd)
vsd$gene <- str_to_title(vsd$gene)
vsd <- as.data.frame(vsd)
row.names(vsd) <- vsd$gene
vsd$gene <- NULL
head(vsd)

# prep to join with sample colData
vsd <- as.data.frame(t(vsd))
vsd$sample <- row.names(vsd)
vsd$mouse <- sapply(strsplit(as.character(vsd$sample),"\\-"), "[", 1)
vsd$ID <- paste(15, vsd$mouse, sep = "")

vsd <- left_join(colData, vsd)
head(vsd)[1:10]

```



```{r Arc}
summary(lm( PC1 ~ Arc, data = vsd))
summary(lm( PC2 ~ Arc, data = vsd))

cor.test(vsd$PC1, vsd$Arc, method = c("pearson"))
cor.test(vsd$PC2, vsd$Arc, method = c("pearson"))

iconDG <- png::readPNG("../figures/00_schematics/DG.png")
iconDG <-  grid::rasterGrob(iconDG, interpolate=TRUE)

vsd$training <- factor(vsd$training, levels = levelstraining)

a <- ggplot(vsd, aes(x = Arc, y = PC1)) +
   geom_point(aes( color = training)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = volcano1) +
  theme_ms() +
   theme(legend.position = "bottom",
         axis.title.x = element_text(face = "italic"),
         legend.title = element_blank(), 
         legend.key.size = unit(0.25, "cm"))  +
  labs(subtitle = "r = 0.81, p = 0.0002") +
   annotation_custom(iconDG, ymin = 6, ymax = 11, xmin = 7.5, xmax = 9)
a
```


## Correlate ALL genes with PC1 and PC2

```{r makecorrrmat}

# I'm using the select function to get PC1, PC1, and all the genes. Use `tail(names(vsd),5)` to see that last genes is "ZZZ3"
head(names(vsd),10)
tail(names(vsd),5)

forcorall <-  vsd %>% select(PC1:Zzz3)
corrrmat <- correlate(forcorall, diagonal = 1) 
head(corrrmat)[1:5]
```

## Top 11 correlations with PC1 and their relationship with PC2

```{r corrr}
corrsTop10 <- corrrmat %>% 
  focus(PC1, PC2)  %>% 
  arrange(desc(PC1)) %>% 
  filter(PC1 > 0.7534) 
corrsTop10

topcorrrs <- corrsTop10$rowname

p1 <- corrrmat %>% 
  focus(PC1, PC2, topcorrrs,  mirror = TRUE) %>% 
   focus(PC1, PC2) %>%
  mutate(rowname = reorder(rowname, PC1)) %>%
  ggplot(aes(rowname, PC1, fill = PC1, label = round(PC1,2) )) +
    geom_col() + coord_flip() +
  scale_fill_gradient2(low = "#67a9cf",  high = "#ef8a62", midpoint = 0) +
  theme_ms() +
  theme(legend.position = "none", 
        axis.text.y  = element_text(face = "italic")) +
  ylim(0,1) +
  labs(x = NULL, y = "Correlation to PC1") +
  labs(subtitle = " ")  +
  geom_text(hjust= -0.1, size=2.5) 
p1 

p2 <- corrrmat %>% 
  focus(PC1, topcorrrs,  mirror = TRUE) %>% 
  rearrange() %>% 
  network_plot.cor_df(colors = c("#67a9cf", "white", "#ef8a62"),
               min_cor = .6, curved = T, legend = T,
               repel = TRUE) + 
  theme(legend.position = "bottom") 
p2 
```



## What genes genes correlated with PC1? How many gene correlated with PC1 and are differentially epxressed in DG?

```{r numbers}
# 58 genes are correlated with PC1 > 0.7
corrsPC1sig <- corrrmat %>% 
  focus(PC1)  %>% 
  arrange(desc(PC1)) %>% 
  filter(PC1 > .7) %>%
   #mutate_each(funs=toupper) %>%
  mutate(gene = rowname) %>% 
  arrange(gene) %>% 
  select(gene,PC1)   
corrsPC1sig$gene

# 214 DEGs in DG
# read DG DEGs
DG_DEGs <- read_csv("../data/suppltable-4.csv") %>%
  dplyr::select(tissue,comparison, gene)
length(DG_DEGs$gene)

# 42 found  in both correlate and deg datasets
PC1corrsDEGS <- inner_join(corrsPC1sig, DG_DEGs) %>% 
  arrange(gene) %>% select(gene,PC1)   
PC1corrsDEGS$gene

top10pc1withpc2 <- corrrmat %>% 
  focus(PC1, PC2, topcorrrs,  mirror = TRUE) %>% 
   focus(PC1, PC2)
head(top10pc1withpc2)
```


## new correlation analysis with p-values

```{r sigcorrs}
# meta data
colData <- read_csv("../data/00_colData.csv")
geneids <- read_csv("../data/00_geneids.csv") %>% distinct(gene) %>% mutate(gene = toupper(gene))

# pca data
pca.Rn <- read_csv("../data/suppletable3.csv") %>% 
  filter(trialNum == 9) %>%  
  select(ID:PC2) %>%
  left_join(colData) %>% drop_na() %>% select(ID, treatment, training, trialNum, RNAseqID, subfield, PC1, PC2)
head(pca.Rn)

prepvsdforjoin <- function(pathtovsd, mysubfield){
  #read all count data
  vsd <- read_csv(pathtovsd) 
  vsd$gene <- vsd$X1
  vsd$gene <- str_to_title(vsd$gene)
  vsd <- vsd %>% arrange(gene) %>%  select(gene,everything())
  vsd <- as.data.frame(vsd)
  vsd$X1 <- NULL
  row.names(vsd) <- vsd$gene
  vsd$gene <- NULL
  vsd <- as.data.frame(t(vsd))

  vsd$RNAseqID <- row.names(vsd)
  vsd <- vsd %>%  select(RNAseqID, everything())
  vsd <- left_join(pca.Rn, vsd)  %>% drop_na()

  vsd$subfield <- factor(vsd$subfield, levels = levelssubfield)
  vsd$treatment <- factor(vsd$treatment, levels = levelstreatment)
  vsd$training <- factor(vsd$training, levels = levelstraining)
  return(vsd)
}

vsdDG <- prepvsdforjoin("../data/03_DG_vsdtraining.csv")


getcandidategenecorrelations <- function(df, candidategenes, whichsubfield){
  
  x <- df %>%
    select(ID, PC1, candidategenes)
  x <- as.data.frame(x)
  row.names(x) <- x$ID
  x$ID <- NULL
  res <- rcorr(as.matrix(x))
  
  cormat <- res$r
  pmat <- res$P
  
  ut <- upper.tri(cormat)
  
  newdf <- data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
  
  newdf <- newdf %>% arrange(p) %>%
    mutate(padj = p.adjust(p, method = "fdr", n = length(p))) %>%
    filter(row == "PC1")
  
  
  
  filename <- paste("../data/04_", whichsubfield, "_corrswithpvalue.csv", sep = "")
  write.csv(newdf, filename)
  
  print(head(newdf, 10))
  return(newdf)
  
}

DGcorrswithpvalue <- getcandidategenecorrelations(vsdDG, topcorrrs, "DG")

newp1 <- ggplot(DGcorrswithpvalue, aes(x = reorder(column, cor), y = cor, label = round(cor,2), fill = cor)) +
  geom_col() +
  coord_flip() +
  scale_fill_gradient2(low = "#67a9cf",  high = "#ef8a62", midpoint = 0) +
  theme_ms() +
  theme(legend.position = "none", 
        axis.text.y  = element_text(face = "italic")) +
  ylim(0,1) +
  labs(x = NULL, y = "Correlation to PC1") +
  geom_text(hjust= -0.1, size=2.5) 
newp1
```


## all figures together

```{r correlations, fig.width=6.69, fig.height=3.5}

fig4 <- plot_grid(a, newp1, p2, nrow = 1, rel_widths = c(1,1,1.5), 
                  labels = "auto", label_size = 8)
fig4   

pdf(file="../figures/04_correlations/correlations.pdf", width=6.69, height=3.5)
plot(fig4)
dev.off()

pdf(file="../figures/fig-4.pdf", width=6.69, height=3.5)
plot(fig4)
dev.off()
```

## data in one supplement


```{r}
corrsPC1sig
PC1corrsDEGS
```



```{r citation}
citation("corrr")
```

```{r write}
suppltable6 <-  corrrmat %>%  focus(PC1, topcorrrs,  mirror = TRUE) %>% arrange(desc(PC1))
suppltable6

write.csv(suppltable6, "../data/suppltable6.csv", row.names = F)
```
