---
title: "Search favorite gene Analysis"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/06_favegenes/', cache = T, cache.lazy = F)
```

```{r packages}
suppressMessages(library(tidyverse))
suppressMessages(library(cowplot))
suppressMessages(library(corrr)) # for easy correlations
suppressMessages(library(Hmisc)) # for correlations with pvalue

source("./figureoptions.R")
source("./functions_RNAseq.R")
```

## Sample information and PC1

```{r vsds}
# meta data
colData <- read_csv("../data/00_colData.csv")

geneids <- read_csv("../data/00_geneids.csv") %>% distinct(gene) %>% mutate(gene = toupper(gene))

# pca data
pca.Rn <- read_csv("../data/01_pca.all.csv") %>% 
  filter(trialNum == 9) %>%  
  select(ID:PC2) %>%
  left_join(colData) %>% drop_na() %>% select(ID, treatment, training, trialNum, Day, RNAseqID, subfield, PC1, PC2)
head(pca.Rn)

prepvsdforjoin <- function(pathtovsd, mysubfield){
  #read all count data
  vsd <- read_csv(pathtovsd) 
  vsd$gene <- vsd$X1
  vsd$gene <- str_to_title(vsd$gene)
  vsd <- vsd %>% arrange(gene) %>%  select(gene,everything())
  vsd <- as.data.frame(vsd)
  vsd$X1 <- NULL
  row.names(vsd) <- vsd$gene
  vsd$gene <- NULL
  vsd <- as.data.frame(t(vsd))

  vsd$RNAseqID <- row.names(vsd)
  vsd <- vsd %>%  select(RNAseqID, everything())
  vsd <- left_join(pca.Rn, vsd)  %>% drop_na()

  vsd$subfield <- factor(vsd$subfield, levels = levelssubfield)
  vsd$treatment <- factor(vsd$treatment, levels = levelstreatment)
  vsd$training <- factor(vsd$training, levels = levelstraining)
  return(vsd)
}

vsdDG <- prepvsdforjoin("../data/03_DG_vsdtraining.csv")
vsdCA1 <- prepvsdforjoin("../data/03_CA1_vsdtraining.csv")
vsdCA3 <- prepvsdforjoin("../data/03_CA3_vsdtraining.csv")


```

## correlation of PC1 and PC2

```{r PC1PC2}
head(vsdDG)[1:10]
```



## different sets of candidatea genes

```{r candidategenes}
classicmemgenes <- c("Prkcz",  "Wwc1" ,  "Prkci",  "Prkcb" , "Nsf" ,   "Gria2" , 
                     "Pin1" ,  "Igf2" ,  "Camk2a" , "Pick1")

stabilizationgenes  <- c("Igf2bp2", "Lama1"  , "Lamb1"  , "Lamc1" ,  "Tnc" ,
                         "Tnxb"  ,  "Tnr" ,    "Gabra1" , "Ptprs"  , "Pnn"  , "Egfr")

ACTINngenes <- c("Limk1","Cfl1", "Rock2")

astrocyticgenes <- c("Aldh1a1", "Aldh1l1" ,"Aldh1l2", "Slc1a2" , "Gfap" ,
                     "Gjb6" ,   "Fgfr3" ,  "Aqp4" ,   "Aldoc")

allcandidates <- c(classicmemgenes, ACTINngenes, stabilizationgenes, astrocyticgenes)
```

```{r icons}
iconDG <- png::readPNG("../figures/00_schematics/DG.png")
iconDG <-  grid::rasterGrob(iconDG, interpolate=TRUE)

iconCA3 <- png::readPNG("../figures/00_schematics/CA3.png")
iconCA3 <-  grid::rasterGrob(iconCA3, interpolate=TRUE)

iconCA1 <- png::readPNG("../figures/00_schematics/CA1.png")
iconCA1 <-  grid::rasterGrob(iconCA1, interpolate=TRUE)

icontrainedyoked <- png::readPNG("../figures/00_schematics/figure_yokedtrained.png")
icontrainedyoked <-  grid::rasterGrob(icontrainedyoked, interpolate=TRUE)

```



## correlations with PC1

```{r supplefig3, fig.height= 3.14, fig.width=6.69}
printcortests <- function(mysubfield, df){
  print(mysubfield)
  print(cor.test(df$PC1, df$Arc, method = c("pearson")))
  print(cor.test(df$PC1, df$Prkcz, method = c("pearson")))
  print(cor.test(df$PC1, df$Camk2a, method = c("pearson")))
}

printcortests("CA3", vsdCA3)
printcortests("CA1", vsdCA1)

plotcorrelation <- function(df, myx, myy){
  p <- ggplot(df, aes(x = myx, y = myy)) +
   geom_point(aes(color = training)) + 
   geom_smooth(method = "lm", color = "grey") +
   scale_color_manual(values = volcano1) +
  theme_ms() +
   theme(legend.position = "none") +
    labs(y = NULL, x = NULL)
  return(p)
}

p1 <- plotcorrelation(vsdDG, vsdDG$PC1, vsdDG$PC2) + 
  labs(x = "PC1", y = "PC2", subtitle = "r = -0.30, p = 0.327")  + 
    annotation_custom(icontrainedyoked, ymin = 3, ymax = 4, xmin = 2.5, xmax = 7.5)


p2 <- plotcorrelation(vsdCA3, vsdCA3$PC1, vsdCA3$Arc) + 
  labs(x = "PC1", y = "Arc", subtitle = "r = -0.30, p = 0.327")  + 
  theme(axis.title.y = element_text(face = "italic"),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.size =  unit(0.25, "cm")) +
  annotation_custom(iconCA3, ymin = 9.3, ymax = 9.7, xmin = 4.25, xmax = 7)

p3 <- plotcorrelation(vsdCA1, vsdCA1$PC1, vsdCA1$Arc)  + 
  labs(x = "PC1", y = "Arc", subtitle = "r = 0.20, p = 0.48") + 
  theme(axis.title.y = element_text(face = "italic")) +
    annotation_custom(iconCA1, ymin = 10.5, ymax = 11.3, xmin = -2.6, xmax = 0) 
  
mylegend = get_legend(p2)
p1p2p3 <- plot_grid(p1,p2 + theme(legend.position = "none"), p3, labels = "auto", label_size = 8, nrow = 1)

supplfig3 <- plot_grid(p1p2p3, mylegend, nrow = 2, rel_heights = c(1,0.1))
supplfig3

pdf(file="../figures/06_favegenes/supplfig3.pdf", width=6.69, height=3.5)
plot(supplfig3)
dev.off()

pdf(file="../figures/supplfig3.pdf", width=6.69, height=3.5)
plot(supplfig3)
dev.off()

```


## Correlate ALL genes with PC1 and PC2

```{r makecorrrmat}
# Use `tail(names(vsd),10)` to see that last genes is "Zzz3"
tail(names(vsdDG),10)

makecorrrmatrix <- function(df){
  forcorall <-  df %>% select(PC1:Zzz3)
  corrrmat <- correlate(forcorall) 
  return(corrrmat)
}
```

```{r makecorrrmat1}
corrrDG <- makecorrrmatrix(vsdDG) 
```

```{r makecorrrmat2}
corrrCA3 <- makecorrrmatrix(vsdCA3) 
```

```{r makecorrrmat3}
corrrCA1 <- makecorrrmatrix(vsdCA1) 
```


## Top correlations with PC1 and their relationship with PC2

```{r corrr, fig.height=6}
corrsTop <- corrrDG %>% 
  focus(PC1)  %>% 
  arrange(desc(PC1)) %>% 
  top_n(20)
  
topcorrrs <- corrsTop$rowname

a <- corrrDG %>% 
    focus(PC1,  topcorrrs,  mirror = TRUE) %>% 
    focus(PC1) %>% 
    mutate(rowname = reorder(rowname, PC1)) %>%
    ggplot(aes(rowname, PC1, fill = PC1)) +
     geom_col() + coord_flip() +
    scale_fill_gradient2(low = "#67a9cf",  high = "#ef8a62", midpoint = 0) +
    theme_ms() +
    theme(legend.position = "none", axis.text.y = element_text(face = "italic")) +
    #ylim(-1,1) +
    labs(x = NULL, y = "Correlation to PC1 (avoidance estimate)") 
  
b <- corrrDG %>% 
    focus(PC1, topcorrrs,  mirror = TRUE) %>% 
    replace(., is.na(.), 1) %>% 
    network_plot.cor_df(colors = c("#67a9cf", "white", "#ef8a62"),
               min_cor = .7, curved = F, legend = T,
               repel = TRUE) + 
    theme(legend.position = "none") 
  
ab <- plot_grid(a,b,  nrow = 1, labels = c("a", "b"), label_size = 8)
 
abcd <- plot_grid(ab, cd, rel_widths = c(0.66, 0.33))
abcd


plotcorrrs2 <- function(df, whichsubfield){
  
  favgenes <- c(classicmemgenes, stabilizationgenes)
  
  df <- df %>% 
    focus(PC1, favgenes,  mirror = TRUE)  %>% 
    arrange(desc(PC1))

  p1 <- df %>% 
    focus(PC1) %>%
    mutate(rowname = reorder(rowname, PC1)) %>%
    ggplot(aes(rowname, PC1, fill = PC1)) +
     geom_col() + coord_flip() +
    scale_fill_gradient2(low = "#67a9cf",  high = "#ef8a62", midpoint = 0) +
    theme_ms() +
    theme(legend.position = "none", axis.text.y = element_text(face = "italic")) +
    #ylim(-1,1) +
    labs(x = NULL, y = "Correlation to PC1 (avoidance estimate)")
  

  p3 <- df %>% 
    replace(., is.na(.), 1) %>% 
    network_plot.cor_df(colors = c("#67a9cf", "white", "#ef8a62"),
               min_cor = 0.0, curved = F, legend = T,
               repel = TRUE) + 
    theme(legend.position = "bottom") 
  
  p13 <- plot_grid(p1,p3,  nrow = 1, labels = c("d", "e"), label_size = 8)
  
  filename <- paste("../data/06_", whichsubfield, "_candidatecorrelations.csv", sep = "")
  
  write.csv(df, filename)

  return(p13)
  
}

ef <- plotcorrrs2(corrrDG, "DG")

efgh <- plot_grid(ef, gh, rel_widths = c(0.66, 0.33))
efgh

plot_grid(abcd,efgh, nrow = 2)
```



## correlations with p-values


```{r Hmisc}
getcandidategenecorrelations <- function(df, candidategenes, whichsubfield){
  
  x <- df %>%
    select(ID, PC1, PC2, candidategenes)
  x <- as.data.frame(x)
  row.names(x) <- x$ID
  x$ID <- NULL
  res <- rcorr(as.matrix(x))
  
  cormat <- res$r
  pmat <- res$P
  
  ut <- upper.tri(cormat)
  
  newdf <- data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
  
  newdf <- newdf %>% arrange(p) %>%
    mutate(padj = p.adjust(p, method = "fdr", n = length(p)))
  
  filename <- paste("../data/06_", whichsubfield, "_corrswithpvalue.csv", sep = "")
  write.csv(newdf, filename)
  
  print(head(newdf, 10))
  return(newdf)
  
}

DGcorrswithpvalue <- getcandidategenecorrelations(vsdDG, allcandidates, "DG")
```

