---
title: "fig1"
output: md_document
---

New approach. Behavior-centric analysis figures first. 


```{r setup}
library(tidyverse) ## for respahing data
library(cowplot) ## for some easy to use themes
library(DESeq2)

library("png")
library("grid")

library(BiocParallel)
register(MulticoreParam(6))

source("functions_RNAseq.R")
source("figureoptions.R")

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/fig1/', message = F, results = F)
```

```{r behav}
# all behavior data
behav <- read.csv("../data/01a_behavior.csv") 

# make mouse name
behav$mouse <- sapply(strsplit(as.character(behav$ID),"15"), "[", 2)

behav <-  behav %>% 
  select(mouse,APA2, TrainSessionCombo, TrainSessionComboNum, Time1stEntr, Path1stEntr, pTimeTarget, NumEntrances)

# subset to standard or conflict paradigm only
standard <- behav %>% filter(APA2 %in% c("standard-yoked", "standard-trained")) 
standard$APA2 <- factor(standard$APA2, levels = c("standard-yoked", "standard-trained"))

conflict <- behav %>% filter(APA2 %in% c("conflict-yoked", "conflict-trained")) 
conflict$APA2 <- factor(conflict$APA2, levels = c("conflict-yoked", "conflict-trained"))


# gather and summarize

calculatemeandev <- function(mydf){
  
  mydf <- mydf %>% gather(behavior, measure, Time1stEntr:NumEntrances)
  mydf$behavior <- factor(mydf$behavior, levels = c("Path1stEntr", "Time1stEntr", "pTimeTarget", "NumEntrances"))

  meandev <- mydf %>%
    dplyr::group_by(APA2, TrainSessionComboNum, behavior) %>%
    dplyr::summarise(m = mean(measure), 
                   se = sd(measure)/sqrt(length(measure)))
  return(meandev)
}

standard.meandev <- calculatemeandev(standard)
conflict.meandev <- calculatemeandev(conflict)


plotmeansd <- function(mymeandev, mybehavior, myylab, mycolors){
  
  mymeandev %>% 
    filter(behavior == mybehavior) %>% 
    ggplot(aes(x=, TrainSessionComboNum, y=m, color=APA2)) + 
      geom_errorbar(aes(ymin=m-se, ymax=m+se, color=APA2), width=.1) +
      geom_point(size = 1.5) +
      geom_line() +
    theme_minimal(base_size = 8) + 
    theme(legend.position = "none") + 
    scale_color_manual(values = mycolors) +
    scale_x_continuous( breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
                       labels = c( "P", "T1", "T2", "T3",
                                   "Rt", "T4", "T5", "T6", "Rn")) +
    labs(x = NULL, y = myylab) 
  }
  
# Time1stEntr, Path1stEntr, pTimeTarget, NumEntrances
a <- plotmeansd(standard.meandev, "Time1stEntr", "Time 1st entr. (s)" , trainedcolors)
b <- plotmeansd(standard.meandev, "Path1stEntr", "Path 1st entr. (m)" , trainedcolors)
c <- plotmeansd(standard.meandev, "pTimeTarget", "Prop. time in zone" , trainedcolors)
d <- plotmeansd(standard.meandev, "NumEntrances", "Num. of entr." , trainedcolors)

h <- plotmeansd(conflict.meandev, "Time1stEntr", "Time 1st entr. (s)" , conflictcolors)
i <- plotmeansd(conflict.meandev, "Path1stEntr", "Path 1st entr. (m)" , conflictcolors)
j <- plotmeansd(conflict.meandev, "pTimeTarget", "Prop. time in zone" , conflictcolors)
k <- plotmeansd(conflict.meandev, "NumEntrances", "Num. of entr." , conflictcolors)
```



```{r DESeq2}
a.colData <- read.csv("../data/02a_colData.csv", header = T)
a.countData <- read.csv("../data/02a_countData.csv", header = T, check.names = F, row.names = 1)

trained <- c("standard.yoked", "standard.trained")
conflict <- c("conflict.yoked", "conflict.trained")
trainedconflict <- c("standard.trained", "conflict.trained")
yokedyoked <- c("standard.yoked", "conflict.yoked")


# trained
DGdds <- returndds("DG", trained) 
CA1dds <- returndds("CA1", trained) 
CA3dds <- returndds("CA3", trained) 

e <-  plot.cons.yokcons(DGdds, "DG", "DG") 
f <-  plot.cons.yokcons(CA3dds, "CA3", "CA3") 
g <-  plot.cons.yokcons(CA1dds, "CA1", "CA1") 

efg <- plot_grid(e + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 f + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 g, nrow = 3)

# conflict
DGdds <- returndds("DG", conflict) 
CA1dds <- returndds("CA1", conflict) 
CA3dds <- returndds("CA3", conflict) 

l <-  plot.conf.yokconf(DGdds, "DG", "DG") 
m <-  plot.conf.yokconf(CA3dds, "CA3", "CA3") 
n <-  plot.conf.yokconf(CA1dds, "CA1", "CA1") 

lmn <- plot_grid(l + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 m + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 n, nrow = 3)

# trained v conflict
DGdds <- returndds("DG", trainedconflict) 
CA1dds <- returndds("CA1", trainedconflict) 
CA3dds <- returndds("CA3", trainedconflict) 

o <-  plot.conf.cons(DGdds, "DG") 
p <-  plot.conf.cons(CA3dds, "CA3") 
q <-  plot.conf.cons(CA1dds, "CA1") 

opq <- plot_grid(o + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 p + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 q, nrow = 3)

# yoked v yoked

DGdds <- returndds("DG", yokedyoked) 
CA1dds <- returndds("CA1", yokedyoked) 
CA3dds <- returndds("CA3", yokedyoked) 

r <-  plot.yokconf.yokcons(DGdds, "DG") 
s <-  plot.yokconf.yokcons(CA3dds, "CA3") 
t <-  plot.yokconf.yokcons(CA1dds, "CA1") 

rst <- plot_grid(r + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 s + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
                 t, nrow = 3)
```

```{r correlations}

```



```{r fig1}
schematicTrained <- ggdraw() +  draw_image("../figures/figure_fig1a.png")
schematicConflict <- ggdraw() +  draw_image("../figures/figure_fig2a.png")

a14 <- plot_grid(a,b,d,d, ncol = 1)
b14 <- plot_grid(h + theme(axis.title.y = element_blank()),
            i + theme(axis.title.y = element_blank()),
            j + theme(axis.title.y = element_blank()),
            k + theme(axis.title.y = element_blank()), ncol = 1)
c13 <- plot_grid(e + theme(axis.title.x = element_blank()),
                    f + theme(axis.title.x = element_blank()),
                 g, ncol = 1)
d13 <- plot_grid(l + theme(axis.title = element_blank()),
                 m + theme( axis.title = element_blank()),
                 n+ theme( axis.title.y = element_blank()),
                 ncol = 1)

opqrst <- plot_grid(opq,rst, ncol = 2, labels = c( "standard v\nconflict", "yoked v \nyoked"),label_size = 8) 


plot_grid(a14, b14, c13, d13, opqrst, nrow = 1,
          labels = c("standard training", "conflict training", "standard\nyoked v trained", "conflict\nyoked v trained", NULL),
          label_size = 8,
          rel_widths = c(1,0.9,0.75,0.75,1))


```