---
title: "fig2"
output: md_document
---

New approach. Behavior-centric analysis figures first. 


```{r setup}
library(tidyverse) ## for respahing data
library(cowplot) ## for some easy to use themes
library(DESeq2)

library(BiocParallel)
register(MulticoreParam(6))

source("functions_RNAseq.R")
source("figureoptions.R")

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/fig2/')
```

```{r behav}
# all behavior data
behav <- read.csv("../data/01a_behavior.csv") 

# make mouse name
behav$mouse <- sapply(strsplit(as.character(behav$ID),"15"), "[", 2)

# subset to conflict paradigm only
conflict <- behav %>% filter(APA2 %in% c("conflict-yoked", "conflict-trained"),
                             TrainSession == "Retention") %>% 
                           select(mouse,APA2, Time1stEntr, Path1stEntr, pTimeTarget, NumEntrances)

conflict$APA2 <- factor(conflict$APA2, levels = c("conflict-yoked", "conflict-trained"))

# gather
conflict <- conflict %>% gather(behavior, measure, Time1stEntr:NumEntrances)

conflict$behavior <- factor(conflict$behavior, levels = c("Path1stEntr", "Time1stEntr", "pTimeTarget", "NumEntrances"))

top <- ggplot(conflict, aes(x = APA2, y = measure, color = APA2)) + 

  geom_boxplot() +
    geom_jitter()  + 
  facet_wrap(~behavior, scales = "free_y", nrow  = 1) + 
  theme_minimal() + 
  theme(legend.position = "none",
        axis.text.x = element_blank()) + 
  scale_color_manual(values = conflictcolors) +
  labs(x = NULL) 
top
```

```{r DESeq2}
a.colData <- read.csv("../data/02a_colData.csv", header = T)
a.countData <- read.csv("../data/02a_countData.csv", header = T, check.names = F, row.names = 1)

trained <- c("conflict.yoked", "conflict.trained")

DGdds <- returndds("DG", trained) 
CA1dds <- returndds("CA1", trained) 
CA3dds <- returndds("CA3", trained) 

DGvsd <- returnvsds(DGdds, "../data/fig1.DG.vsd.trained.csv")
returnvsds(CA1dds, "../data/fig1.CA1.vsd.trained.csv")
returnvsds(CA3dds, "../data/fig1.CA3.vsd.trained.csv")

res_summary_subfield(DGdds, c("APA2", "conflict.trained", "conflict.yoked"))
res_summary_subfield(CA1dds, c("APA2", "conflict.trained", "conflict.yoked"))
res_summary_subfield(CA3dds, c("APA2", "conflict.trained", "conflict.yoked"))


```


```{r fig1}
#plot_grid(top,abc, nrow = 2)
```