---
title: "PCseq"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(DESeq2)
library(binr)

knitr::opts_chunk$set(echo = TRUE)
```

```{r data}
a.countData <- read.csv("../data/02a_countData.csv", header = T, check.names = F, row.names = 1)

a.colData <- read.csv("../data/02a_colData.csv", header = T)
a.colData

pcadata <- read_csv("../data/01a_pcadf.csv") %>%
  group_by(ID) %>%
  mutate(PC1ave = mean(PC1),
         PC2ave = mean(PC2)) %>%
  distinct(ID,PC1ave,PC2ave)
pcadata

summary(pcadata$PC1ave)
a.colData <- left_join(a.colData, pcadata)

# bin PCA data in to postivte and negative PC values
a.colData$PC1bin <- ifelse(a.colData$PC1ave < 0, "negative", "positive") 

# bin PCA data into quartiles
a.colData <- a.colData %>% mutate(quartile = ntile(PC1ave, 4))
a.colData$quartile <- ifelse(a.colData$quartile == 1, "one",
                             ifelse(a.colData$quartile == 2, "two",
                                    ifelse(a.colData$quartile == 3, "three",
                                           ifelse(a.colData$quartile == 4, "four", NA))))

a.colData$quartile <- as.factor(a.colData$quartile)
```

```{r}
returnddsquartile <- function(mytissue){
  print(mytissue)
  colData <- a.colData %>% 
    filter(subfield %in% c(mytissue))  %>% 
    droplevels()
  
  savecols <- as.character(colData$RNAseqID) 
  savecols <- as.vector(savecols) 
  countData <- a.countData %>% dplyr::select(one_of(savecols)) 
  
  ## create DESeq object using the factors subfield and APA
  dds <- DESeqDataSetFromMatrix(countData = countData,
                                colData = colData,
                                design = ~ quartile)
  
  dds <- dds[ rowSums(counts(dds)) > 1, ]  # Pre-filtering genes with 0 counts
  dds <- DESeq(dds, parallel = TRUE)
  return(dds)
}

## create DESeq object using the factors subfield and APA
dds <- DESeqDataSetFromMatrix(countData = a.countData,
                                colData = a.colData,
                                design = ~ subfield * treatment)
  
dds <- dds[ rowSums(counts(dds)) > 10, ]  # Pre-filtering genes with 0 counts
dds <- DESeq(dds, parallel = TRUE)
#vsd <- vst(dds, blind=FALSE) ## variance stabilized

#res_summary(c("subfield", "CA1", "DG"))
res_summary(c("PC1bin", "positive", "negative"))
#res_summary(c("training", "yoked", "trained"))
res_summary(c("treatment", "standard.trained", "standard.yoked")) #500
res_summary(c("treatment", "conflict.trained", "conflict.yoked")) # 5
res_summary(c("treatment", "standard.trained", "conflict.trained")) # 0
res_summary(c("treatment", "standard.yoked", "conflict.yoked")) # 823
res_summary(c("quartile", "one", "two")) #6
res_summary(c("quartile", "one", "three")) # 0
res_summary(c("quartile", "one", "four")) #12
res_summary(c("quartile", "two", "four")) #7
res_summary(c("quartile", "three", "four")) #27

# ~ treatment + subfield 125
# ~ treatment + subfield + treatment:subfield 837
# ~ treatment * subfield 837
# ~ subfield * treatment 837
# ~ subfield + treatment 125
# ~ subfield * PC1ave 17
```

```{r}
ddsDG <- returnddsquartile("DG")

res_summary <- function(mycontrast){
  res <- results(ddsDG, contrast = mycontrast, independentFiltering = T)
  print(mycontrast)
  print(sum(res$padj < 0.1, na.rm=TRUE))
  print(summary(res))
  oredered <- (res[order(res$padj),])
  print(head(rownames(oredered),55))
}

res_summary(c("quartile", "one", "two")) # 1
res_summary(c("quartile", "one", "three")) # 35
res_summary(c("quartile", "one", "four")) # 77
res_summary(c("quartile", "two", "four")) # 110
res_summary(c("quartile", "three", "four")) # 0

ddsCA1 <- returnddsquartile("CA1")

res_summary <- function(mycontrast){
  res <- results(ddsCA1, contrast = mycontrast, independentFiltering = T)
  print(mycontrast)
  print(sum(res$padj < 0.1, na.rm=TRUE))
  #print(summary(res))
  oredered <- (res[order(res$padj),])
  print(head(rownames(oredered),55))
}

res_summary(c("quartile", "one", "two")) # 0
res_summary(c("quartile", "one", "three")) # 0
res_summary(c("quartile", "one", "four")) # 2
res_summary(c("quartile", "two", "four")) # 2
res_summary(c("quartile", "three", "four")) # 13

ddsCA3 <- returnddsquartile("CA3")

res_summary <- function(mycontrast){
  res <- results(ddsCA3, contrast = mycontrast, independentFiltering = T)
  print(mycontrast)
  print(sum(res$padj < 0.1, na.rm=TRUE))
  #print(summary(res))
  oredered <- (res[order(res$padj),])
  print(head(rownames(oredered),55))
}

res_summary(c("quartile", "one", "two")) # 45
res_summary(c("quartile", "one", "three")) # 55
res_summary(c("quartile", "one", "four")) # 16
res_summary(c("quartile", "two", "four")) # 0
res_summary(c("quartile", "three", "four")) # 0


```